# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pivot/pivot.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot || ORIG_REF_NAME==pivot} -quiet] -quiet

# IP: bd/pivot/ip/pivot_processing_system7_0_0/pivot_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot_processing_system7_0_0 || ORIG_REF_NAME==pivot_processing_system7_0_0} -quiet] -quiet

# IP: bd/pivot/ip/pivot_PIVOT_0_1/pivot_PIVOT_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot_PIVOT_0_1 || ORIG_REF_NAME==pivot_PIVOT_0_1} -quiet] -quiet

# IP: bd/pivot/ip/pivot_ps7_0_axi_periph_0/pivot_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot_ps7_0_axi_periph_0 || ORIG_REF_NAME==pivot_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot_rst_ps7_0_100M_0 || ORIG_REF_NAME==pivot_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pivot/ip/pivot_auto_pc_0/pivot_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pivot_auto_pc_0 || ORIG_REF_NAME==pivot_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/pivot_ooc.xdc
