# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.srcs/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/pivot_PIVOT_0_1.xci
# IP: The module: 'pivot_PIVOT_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.srcs/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/pivot_PIVOT_0_1.xci
# IP: The module: 'pivot_PIVOT_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/div_gen_0/div_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_PIVOT_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
