# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.srcs/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0.xci
# IP: The module: 'pivot_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.srcs/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0.xci
# IP: The module: 'pivot_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dusan/Desktop/projekat_radi/divider/pivot/pivot.gen/sources_1/bd/pivot/ip/pivot_rst_ps7_0_100M_0/pivot_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pivot_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
